### ISSUE TITLE
حجم بالا فایل های کانفیگ

### ISSUE THREAD

**Issue by vkoori** [mheidari98/.proxy#1]
حجم فایل کانفیگ انقدر بالا هست که توی clipboard اندروید جا نمیشه برای windows هم وقتی کانفیگ ها رو ایمپورت کردم انقدر تعدادشون بالا بود (1800 خورده ای) اپ crash کرد مجبور شدم همه کانفیگ ها رو دستی از توی source پا کنم. این وسط کانفیگ های سالمی هم که داشتم پرید.
لازمه که فایل های کانفیگ خورد بشن.

**Comment by OrchidWarrior** [comment]
درود ، لطفاً از برنامه Matsuri استفاده کنید که بهینه تر هست. تمام node ها رو دانلود کنید ( فایل خروجی txt هست ). سپس از طریق فایل کانفیگ ها را import  کنید. گزینه save file as در کامپیوتر و view raw file و سپس دانلود در اندروید برای دانلود کانفیگ ها قابل استفاده است.

**Comment by mheidari98** [comment]
سلام، امیدوارم حالتون خوب باشه
راسیتش نمیدونم کلاینتی میتونه این تعداد کانفیگ رو بپذیره یا نه
بشخصه این کانفیگ هارو از سورس های مختلف اسکرپ و یکجا ذخیره کردم تا بعدش با استفاده از ابزار زیر کانفیگ های سالم رو شناسایی و استفاده کنم.
+ https://github.com/mheidari98/proxyUtil/wiki/v2rayChecker.py

---

شاید کانفیگ های ریپو زیر، گزینه مناسب تری باشه برای ایمپورت در کلاینت ها :
> https://github.com/mahdibland/V2RayAggregator
